#!/usr/bin/env bash
# Verifies requirements-lock.txt is exactly what `uv pip compile` produces right now from
# pyproject.toml - the deterministic-regeneration half of G7-W02's own acceptance text ("confirm
# dependency locking is real... verify it is regenerated deterministically, not hand-edited, and
# that CI fails on drift"). Before this script existed, nothing checked this at all (confirmed by
# a direct grep of scripts/ and .github/workflows/ turning up only *consumers* of the lock -
# `pip install -r requirements-lock.txt` in ci.yml/monitor.yml/verify-app-installation.yml - never
# a producer or a drift check); the gap was real, not assumed, and this is what closes it.
#
# Needs network access the same way ci.yml's own "Install from the lock" step does (uv resolves
# against PyPI) - CI-only, not part of scripts/ci_check.sh's offline local suite, matching that
# script's own documented precedent for the one step that needs the network.
#
# Usage: scripts/check_lock_drift.sh
set -euo pipefail

LOCK_FILE="requirements-lock.txt"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

cp "$LOCK_FILE" "$WORKDIR/candidate.txt"

# uv pip compile treats an existing output file as a preference, not a target to discard (see
# `uv pip compile --help`'s own `-U/--upgrade` description: "ignoring pinned versions in any
# existing output file" - the implication, confirmed live, is that WITHOUT -U every already-valid
# pin is kept and only a genuinely missing or now-invalid entry changes). Regenerating onto a copy
# of the committed file, not a fresh path, is therefore the correct way to ask "is this file
# exactly what pyproject.toml's own declared dependencies compile to", not "has any transitive
# package anywhere published a newer release since this was last regenerated".
python -m uv pip compile pyproject.toml --extra dev --universal --generate-hashes \
  -o "$WORKDIR/candidate.txt" >/dev/null

# uv's own autogenerated header comment echoes the literal -o path it was given; normalize it back
# to the real relative path so a scratch directory's own name never counts as drift - only an
# actual change to the compile command itself (extras, --universal, --generate-hashes) should.
sed -i "1,2s#-o .*\$#-o $LOCK_FILE#" "$WORKDIR/candidate.txt"

if ! diff -u "$LOCK_FILE" "$WORKDIR/candidate.txt" > "$WORKDIR/drift.diff"; then
  echo "requirements-lock.txt does not match a fresh 'uv pip compile' of pyproject.toml."
  echo "It is either hand-edited or missing a dependency pyproject.toml declares (or vice versa)."
  echo "Regenerate it with:"
  echo "  uv pip compile pyproject.toml --extra dev --universal --generate-hashes -o requirements-lock.txt"
  echo
  cat "$WORKDIR/drift.diff"
  exit 1
fi

echo "requirements-lock.txt matches a fresh uv pip compile of pyproject.toml - no drift."
